CREATE TABLE IF NOT EXISTS prm_services (
    row_id INT AUTO_INCREMENT PRIMARY KEY,
    id INT NOT NULL,  -- source-system PRM service ID; can repeat across rows when a service is paused/resumed (see dedup logic)
    flight VARCHAR(20) NOT NULL,
    flight_number INT NOT NULL,
    agent_name VARCHAR(100) NULL,
    agent_no VARCHAR(20) NULL,
    passenger_name VARCHAR(200) NOT NULL,
    prm_agent_type VARCHAR(20) NOT NULL DEFAULT 'SELF',
    start_time INT NOT NULL,
    paused_at INT NULL,
    end_time INT NOT NULL,
    service VARCHAR(20) NOT NULL,
    seat_number VARCHAR(10) NULL,
    scanned_by VARCHAR(50) NULL,
    scanned_by_user VARCHAR(100) NULL,
    remarks TEXT NULL,
    pos_location VARCHAR(50) NULL,
    no_show_flag VARCHAR(5) NULL,
    loc_name VARCHAR(10) NOT NULL,
    arrival VARCHAR(10) NULL,
    airline VARCHAR(10) NOT NULL,
    emp_type VARCHAR(20) NULL DEFAULT 'Employee',
    departure VARCHAR(10) NULL,
    requested INT NOT NULL DEFAULT 0,
    service_date DATE NOT NULL,
    INDEX idx_loc_date (loc_name, service_date),
    INDEX idx_date_range (service_date, loc_name, airline),
    INDEX idx_id (id),
    INDEX idx_airline (airline),
    INDEX idx_service (service),
    INDEX idx_agent (agent_no),
    INDEX idx_prm_type (prm_agent_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
